version: "3"
services:
  telldus-core-mqtt:
    image: mliljedahl/telldus-core-mqtt:1.2.1
    container_name: telldus-core-mqtt
    restart: unless-stopped
    environment:
      - TDM_MQTT_SERVER=localhost
      - TDM_MQTT_USER=telldus-core-mqtt
      - TDM_MQTT_PASS=telldus-core-mqtt
    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
    volumes:
      - ./tellstick.conf:/etc/tellstick.conf:ro