name: Docker Image CI

on:
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive
      
      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/vegardbeider/telldus-core-mqtt:$(date +%F)

      - name: Push Docker image
        run: docker push ghcr.io/vegardbeider/telldus-core-mqtt:$(date +%F)
